server:
  servlet:
    context-path: /api

mybatis-plus:
  mapper-locations: classpath:/mapper/**
  global-config:
    db-config:
      id-type: auto
spring:
  profiles:
    active: dev

  #邮箱验证码配置
  mail:
    host: smtp.qq.com # qq邮箱的SMTP
    username: 2405824084@qq.com # 发送方的qq邮箱
    password: otxrwywsqpubdjgb # smtp密码（是16位授权码，不是邮箱密码）
    receiver: zhangchengwei.work@hotmail.com # 接收方邮箱，随意填写
    default-encoding: UTF-8 # 编码格式
    protocol: smtp # SMTP邮件协议
    properties:
      mail:
        smtp:
          auth: true  # 开启身份验证
          starttls:
            enable: true # 启用 STARTTLS 加密
            required: true # 强制要求 STARTTLS 加密
    port: 587