server:
  port: 8071
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/nexnote?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

# redis
  data:
    redis:
      host: localhost # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数
          max-idle: 8 # 连接池最大空闲连接数
          min-idle: 0 # 连接池最小空闲连接数
          max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
